MyStore/MyStore.Web/Controllers/CategoryController.cs
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mystore.Web.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyStore.Services;
using MyStore.Services.DBModels;
using MyStore.Web.Help;
using AspNetCoreHero.ToastNotification.Abstractions;
using MyStore.Services.Repository.Interfaces;

namespace MyStore.Web.Controllers
{
    public class CategoryController : BaseController
    {
 
        private readonly ICategory _categoryService;
        private readonly IRazorRenderService _renderService;
        private readonly INotyfService _notifyService;

        private readonly ILogger<CategoryController> _logger;
        public CategoryController(ILogger<CategoryController> logger, ICategory categoryService, IRazorRenderService renderService, INotyfService notifyService)
        {
          //  _currentUser = scopedUser;
            _logger = logger;
            _categoryService = categoryService;
            _renderService = renderService;
            _notifyService = notifyService;
        }
     
        public IActionResult Index()
        {
            return View();
        }

       
        public async Task<IActionResult> getCategories(IDataTablesRequest request)
        {
            try
            {
                var searchValue = HttpContext.Request.Query["search[value]"].FirstOrDefault();
                  var result = await _categoryService.GetCategories(searchValue, request.Start, request.Length);
                  var response = DataTablesResponse.Create(request, result.Count, result.Count, result);
                 return new DataTablesJsonResult(response, true);
               /// return View();
            }
            catch (Exception ex)
            {
                _notifyService.Error("Internal server error.");
                _logger.LogError(ex.Message);
                throw;
            }
        }

       
        public async Task<ActionResult> CreateOrEdit(int id = 0)
        {
            try
            {
                if (id == 0)
                    return PartialView("_CreateOrEdit", new ProductCategory());
                else
                {
                    var result = await _categoryService.Get(id);
                    if (result == null)
                    {
                        return NotFound();
                    }
                    return PartialView("_CreateOrEdit", result);
                }
                return View();
            }
            catch (Exception ex)
            {
                _notifyService.Error("Internal server error.");
                _logger.LogError(ex.Message);
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateOrEdit(int id, ProductCategory categoryvm)
        {
           // ErrorCode error = ErrorCodes.SUCCESS;
            string alertMessage = "";
            try
            {
                if (!ModelState.IsValid)
                    return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "_CreateOrEdit", categoryvm) });

                //Insert
                if (id == 0)
                {
                    //divisionVM.CreatedAt = DateTime.Now;
                    //divisionVM.CreatedBy = _currentUser.GetId();
                    //divisionVM.IsActive = true;
                   var error = await _categoryService.Add(categoryvm);
                    alertMessage = "Product Category added Successfully";
                }
                //Update
                else
                {

                    //divisionVM.ModifiedAt = DateTime.Now;
                    //divisionVM.ModifiedBy = _currentUser.GetId();
                    //divisionVM.IsActive = true;
                    //error = await _divisionService.UpdateDivision(divisionVM);
                    var error = await _categoryService.Update(categoryvm);
                    alertMessage = "Product Category update successfully";
                }

                //if (error != ErrorCodes.SUCCESS)
                //{
                //    _notifyService.Error(error.Message);
                //    return RedirectToAction("Index");
                //}

                //if (error == ErrorCodes.SUCCESS)
                //{
                //    _notifyService.Success(alertMessage);
                    return RedirectToAction("Index");
                //}
                //else
                //    return View(divisionVM);
            }

            catch (Exception ex)
            {
                _notifyService.Error("Internal server error.");
                _logger.LogError(ex.Message);
                // throw ex;
            }

            return RedirectToAction("Index", this);
        }

    }
}

MyStore/MyStore.Web/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyStore.Web.Controllers
{
    public class DashboardController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyStore/MyStore.Web/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; @DateTime.Now.Year; by My Shop
        <br />
    </div>
    <div class="footer-right">
        1.0.0
    </div>
</footer>

MyStore/MyStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR System</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <environment names="Development,TanveerDev,RashidDev,UserDemo">

        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
            <link href="~/lib/datatables/css/jquery.dataTables.css" rel="stylesheet" />
            <link href="~/lib/datatables/css/dataTables.bootstrap.css" rel="stylesheet" />
            <link href="~/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
            <link rel="stylesheet" href="~/lib/select2/css/select2.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-tagsinput/bootstrap-tagsinput.css" />
            <link href="~/lib/intl-tel-input/build/css/intlTelInput.min.css" rel="stylesheet" />
            <link href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />*@

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>

    <environment names="Development,TanveerDev,RashidDev,UserDemo">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        @*<script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/lib/jquery.nicescroll/jquery.nicescroll.js"></script>
            <script src="~/lib/jquery.form-repeater/jquery.form-repeater.js"></script>

            <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
            <script src="~/lib/datatables/js/dataTables.dataTables.js"></script>
            <script src="~/lib/datatables/js/dataTables.bootstrap.js"></script>
            <script src="~/lib/datatables/js/dataTables.bootstrap4.js"></script>

            <script src="~/lib/aacassandra/jquery.pwstrength/jquery.pwstrength.js"></script>
            <script src="~/lib/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
            <script src="~/lib/select2/js/select2.full.js"></script>
            <script src="~/lib/intl-tel-input/build/js/intlTelInput-jquery.js"></script>
            <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>*@
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</head>
<body>
    <div id="app">
        <div class="main-wrapper">
            <!-- Top Navbar -->
            <partial name="_TopNavbar" />

            <!-- Left Sidebar -->
            <partial name="_LeftSidebar" />


            <div class="main-content">
                <!-- Main view  -->
                @RenderBody()
            </div>

            <!-- Footer -->
            <partial name="_Footer" />
        </div>
    </div>

    <div class="modal" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>

    @*//@await Component.InvokeAsync("Notyf")*@
    <script src="~/js/scripts.js" asp-append-version="true"></script>
    <script src="~/js/custom.js" asp-append-version="true"></script>


    <script type="text/javascript">
        $('input[type=text],input[type=radio],input[type=checkbox],textarea,select,input[type=email],input[type=number]').each(function () {
            var req = $(this).attr('data-val-required');
            var exclude = $(this).attr('data-exclude');
            if (undefined != req && undefined == exclude) {
                var label = $('label[for="' + $(this).attr('id') + '"]');
                var text = label.text();
                if (text.length > 0) {
                    label.append('<span style="color:red"> *</span>');
                }
            }
        });
    </script>

</body>
</html>

MyStore/MyStore.Web/Views/Shared/_LeftSidebar.cshtml
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="index.html"><img src="" alt="logo" width="200"></a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html"><img src="" alt="logo" width="62"></a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>

            <li><a class="nav-link" href="@Url.Action("Index", "Dashboard")"><i class="fas fa-chart-line"></i> <span>Dashboard</span></a></li>

            <li class="menu-header">Administration</li>


            <li class="nav-item dropdown">

                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Administration</span></a>

                <ul class="dropdown-menu">

                    <li><a class="nav-link" href="@Url.Action("Index", "Category")"><i class="far fa-file-alt"></i> <span>Category</span></a></li>


                    <li><a class="nav-link" href="@Url.Action("Index", "Department")"><i class="far fa-file-alt"></i> <span>Product</span></a></li>

                    <li><a class="nav-link" href="@Url.Action("Index", "Department")"><i class="far fa-file-alt"></i> <span>Services</span></a></li>

                    <li><a class="nav-link" href="@Url.Action("Index", "Department")"><i class="far fa-file-alt"></i> <span>Transaction Types</span></a></li>

                    <li><a class="nav-link" href="@Url.Action("Index", "Department")"><i class="far fa-file-alt"></i> <span>Supplier</span></a></li>


                    <li><a class="nav-link" href="@Url.Action("Index", "Department")"><i class="far fa-file-alt"></i> <span>Company</span></a></li>

                </ul>
            </li>


            <li class="menu-header">Purchase Management</li>

            <li class="nav-item dropdown">

                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Purchase</span></a>

                <ul class="dropdown-menu">

                    <li><a class="nav-link" href="@Url.Action("Index", "Role")"><i class="fas fa-th"></i> <span>Purchase Order </span></a></li>

                    <li><a class="nav-link" href="@Url.Action("Index", "WebUser")"><i class="fas fa-th"></i> <span>Purchase Payments </span></a></li>



                </ul>
            </li>


            <li class="menu-header">Sell Management</li>

            <li class="nav-item dropdown">

                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Sell</span></a>

                <ul class="dropdown-menu">

                    <li><a class="nav-link" href="@Url.Action("Index", "Role")"><i class="fas fa-th"></i> <span>Sell Order </span></a></li>

                    <li><a class="nav-link" href="@Url.Action("Index", "WebUser")"><i class="fas fa-th"></i> <span>Sell Payments </span></a></li>



                </ul>
            </li>


            <li class="menu-header">Report Management</li>

            <li class="nav-item dropdown">

                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Reports</span></a>

                <ul class="dropdown-menu">

                    <li><a class="nav-link" href="@Url.Action("Index", "JobRequisitionRequest")"><i class="fas fa-th"></i> <span>Purchase Detail Report</span></a></li>

                    <li><a class="nav-link" href="@Url.Action("Index", "JobApplication")"><i class="fas fa-th"></i> <span>Sell Detail Report</span></a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">

                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Job Lists</span></a>

                <ul class="dropdown-menu">

                    <li><a class="nav-link" href="@Url.Action("Index", "JobPost")"><i class="fas fa-th"></i> <span>Un-Posted Jobs</span></a></li>

                    <li><a class="nav-link" href="@Url.Action("Index", "PostedJob")"><i class="fas fa-th"></i> <span>Posted Jobs</span></a></li>

                    <li><a class="nav-link" href="@Url.Action("ShortListedCandidate", "JobApplication")"><i class="fas fa-th"></i> <span>Shortlisted</span></a></li>
                    <li><a class="nav-link" href="@Url.Action("CandidateInterviews", "JobApplication")"><i class="fas fa-th"></i> <span>Interviews</span></a></li>
                </ul>
            </li>


        </ul>


    </aside>
</div>

MyStore/MyStore.Web/Views/Shared/_TopNavbar.cshtml
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <div class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        </ul>
    </div>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <div class="d-sm-none d-lg-inline-block">Hi, </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item has-icon" href="">
                    <i class="far fa-user"></i>
                    @*<a href="features-profile.html" class="dropdown-item has-icon">
            <i class="far fa-user"></i>*@ Profile
                </a>
                @*<a href="features-settings.html" class="dropdown-item has-icon">
        <i class="fas fa-cog"></i>*@
                <a class="dropdown-item has-icon" href="">
                    <i class="fas fa-cog"></i>
                    Change Password
                </a>
                <div class="dropdown-divider"></div>
                <div class="dropdown-item has-icon text-danger">
                    <i class="fas fa-sign-out-alt"></i>
                    <form class="form-inline" asp-action="Logout" asp-controller="user" method="post" style="margin-top: -5px;">
                        <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                    </form>
                </div>
            </div>
        </li>
        
    </ul>
</nav>